### PR TITLE
Advanced Building Blocks: Enumerables

### PR DESCRIPTION
**Pull request by krys2fa**
# Milestones

- Created my_each method.
- Created my_each_with_index method.
- Created my_select method.
- Created my_all? method.
- Created my_any? method.
- Created my_none? method.
- Created my_count method.
- Created my_map method.
- Created my_inject method.
- Tested the my_inject method with the multiply_els method.
- Modified the my_map method to take procs.

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @krys2fa, good start on this one:+1:. Let's take care of the following:**
- **my_each, my_each_with_index and my_select** should return enumerators when no block is given.
- **my_all?:** when a pattern that is not a Regex or a Class is passed as argument, it should return true only if all the collection matches the pattern.
example: `[1, 1, 2].my_all?(1)` should return `false` since `2` does not match `1`
- When a block is given for **my_any?**, it should return `true` only if there is at least one element for which the block returns `true`,
example: `[1, 2, 3, 4].my_any? { |x| x > 4 }` should return `false`
- When no block or argument is given, my_any? should return true only if there is at least one element in the collection that is a truthy.
example: `[false, nil].my_any?` should return `false`
- when a pattern other than Regex or a Class is given to my_any?, it should return false if none of the collection matches the pattern.
example: `[2, 3, 4].my_any?('a')` should return `false`
- when a pattern other than Regex or a Class is given to my_none, it should return true **only** if none of the collection matches the pattern.
example: `[2, 3, 4].my_none(4)` should return `false`.
- **my_map** should return **a new array** with the results of running block once for every element in enum.
example: `[1, 2, 3, 4].my_map { |x| x + 1 }` should return `[2, 3, 4, 5]`
- **my_map** should return an enumerator when no block is given.
- **my_inject** is not functioning properly. It should return a single value which is the combination of all the elements using the binary operation specified by a block. Currently, your my_inject returns the same object on which it is called.
 Also, take care of the scenario where two arguments are passed to my_inject.
You can look at the [ruby documentation](https://ruby-doc.org/core-2.6.5/Enumerable.html#method-i-inject) to see how the method is expected to function.


_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Comment by krys2fa** [comment]
Thanks for the review @mosesogwo. 
I have implemented all the requested changes.

**Comment by lekegitrepo** [comment]
### Hi @krys2fa :100: :1st_place_medal:
#### You have done a good job. This project is approved :star:

### Reviewed by Temitayo Adeleke.

- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Review by lekegitrepo — APPROVED** [review]
### Status: Approved.

**Comment by krys2fa** [comment]
Thank you @lekegitrepo.

**Pull request merged**
